# Generated by Django 2.0 on 2021-01-14 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DDT', models.FileField(upload_to='DDT_Acquisti/%Y/%m/%d')),
                ('fattura', models.FileField(upload_to='Fattura_Acquisti/%Y/%m/%d')),
                ('prezzo', models.IntegerField(default='0')),
                ('creato', models.DateField(verbose_name='Data acquisto')),
                ('pagamento', models.BooleanField(default=False, verbose_name='Pagato')),
            ],
            options={
                'verbose_name': 'Acquisto',
                'verbose_name_plural': 'Acquisti',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiceID', models.CharField(max_length=100, verbose_name='Codice')),
                ('denominazione', models.CharField(blank=True, max_length=150)),
                ('citta', models.CharField(blank=True, max_length=100, verbose_name='città')),
                ('provincia', models.CharField(blank=True, max_length=10)),
                ('picf', models.CharField(blank=True, max_length=100, verbose_name='P.iva / CF')),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('fatturaElettronica', models.CharField(blank=True, max_length=150, verbose_name='Fattura elettronica')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('cognome', models.CharField(blank=True, max_length=100)),
                ('creato', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clienti',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiceProdotto', models.CharField(max_length=100, verbose_name='Codice prodotto')),
                ('descrizione', models.CharField(blank=True, max_length=200)),
                ('quantita', models.IntegerField(blank=True, default='1', verbose_name='quantità')),
                ('prezzo', models.IntegerField(default='0')),
                ('iva', models.IntegerField(default='22')),
                ('ultima_modifica', models.DateTimeField(auto_now_add=True, verbose_name='Ultima modifica')),
            ],
            options={
                'verbose_name': 'Merce',
                'verbose_name_plural': 'Merci',
            },
        ),
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DDT', models.FileField(upload_to='DDT_vendita/%Y/%m/%d')),
                ('fattura', models.FileField(blank=True, upload_to='fatture_vendita/%Y/%m/%d')),
                ('RIT', models.FileField(upload_to='RIT_vendita/%Y/%m/%d')),
                ('creato', models.DateField(verbose_name='data vendita')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fattura_cliente', to='main.Cliente')),
                ('dispositivo', models.ManyToManyField(default='0', limit_choices_to={'quantita__gte': 1}, related_name='fattura_disp', to='main.Dispositivo', verbose_name='Merce')),
            ],
            options={
                'verbose_name': 'Vendita',
                'verbose_name_plural': 'Vendite',
            },
        ),
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(blank=True, max_length=150)),
                ('citta', models.CharField(blank=True, max_length=100, verbose_name='Città')),
                ('provincia', models.CharField(blank=True, max_length=10)),
                ('picf', models.CharField(blank=True, max_length=100, verbose_name='P.iva / CF')),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('fatturaElettronica', models.CharField(blank=True, max_length=150, verbose_name='Fattura elettronica')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('cognome', models.CharField(blank=True, max_length=100)),
                ('creato', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
            ],
            options={
                'verbose_name': 'fornitore',
                'verbose_name_plural': 'fornitori',
            },
        ),
        migrations.CreateModel(
            name='Prodotti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiceProdotto', models.CharField(max_length=100, verbose_name='Codice prodotto')),
                ('descrizione', models.CharField(blank=True, max_length=200)),
                ('quantita', models.IntegerField(blank=True, default='1', verbose_name='quantità')),
                ('prezzo', models.IntegerField(default='0')),
                ('iva', models.IntegerField(default='22')),
                ('acquisto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti_acquistati', to='main.Acquisti')),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='fornitore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Fornitore'),
        ),
        migrations.AddField(
            model_name='acquisti',
            name='fornitore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Fornitore'),
        ),
    ]
