# Generated by Django 2.0 on 2021-01-13 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DDT', models.FileField(upload_to='DDT_Acquisti/%Y/%m/%d')),
                ('fattura', models.FileField(upload_to='Fattura_Acquisti/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(blank=True, max_length=150)),
                ('citta', models.CharField(blank=True, max_length=100, verbose_name='città')),
                ('provincia', models.CharField(blank=True, max_length=10)),
                ('picf', models.CharField(blank=True, max_length=100, verbose_name='P.iva / CF')),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('fatturaElettronica', models.CharField(blank=True, max_length=150, verbose_name='Fattura elettronica')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('cognome', models.CharField(blank=True, max_length=100)),
                ('creato', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clienti',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiceProdotto', models.CharField(max_length=100, verbose_name='Codice prodotto')),
                ('descrizione', models.CharField(blank=True, max_length=200)),
                ('quantita', models.IntegerField(blank=True, default='1', verbose_name='quantità')),
                ('creato', models.DateTimeField(auto_now_add=True, verbose_name='data creazione')),
            ],
            options={
                'verbose_name': 'Merce',
                'verbose_name_plural': 'Merci',
            },
        ),
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fattura', models.FileField(blank=True, upload_to='fatture_vendita/%Y/%m/%d')),
                ('DDT', models.FileField(upload_to='DDT_vendita/%Y/%m/%d')),
                ('creato', models.DateField(verbose_name='data vendita')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fattura_cliente', to='main.Cliente')),
                ('dispositivo', models.ManyToManyField(default='0', limit_choices_to={'quantita__gte': 1}, related_name='fattura_disp', to='main.Dispositivo', verbose_name='Merce')),
            ],
            options={
                'verbose_name': 'Vendita',
                'verbose_name_plural': 'Vendite',
            },
        ),
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(blank=True, max_length=150)),
                ('citta', models.CharField(blank=True, max_length=100, verbose_name='Città')),
                ('provincia', models.CharField(blank=True, max_length=10)),
                ('picf', models.CharField(blank=True, max_length=100, verbose_name='P.iva / CF')),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('fatturaElettronica', models.CharField(blank=True, max_length=150, verbose_name='Fattura elettronica')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('cognome', models.CharField(blank=True, max_length=100)),
                ('creato', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
            ],
            options={
                'verbose_name': 'fornitore',
                'verbose_name_plural': 'fornitori',
            },
        ),
        migrations.CreateModel(
            name='Installazioni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installato', models.BooleanField(default=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to='installazioni/%Y/%m/%d')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data installazione')),
                ('creato', models.DateTimeField(auto_now_add=True, verbose_name='data creazione')),
                ('dispVenduti', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Dispositivo', verbose_name='Dispositivo')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='fornitore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Fornitore'),
        ),
        migrations.AddField(
            model_name='acquisti',
            name='fornitore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Fornitore'),
        ),
    ]
