# Generated by Django 2.0 on 2021-02-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornitore',
            name='citta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Città'),
        ),
        migrations.AlterField(
            model_name='fornitore',
            name='cognome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fornitore',
            name='creato',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data creazione'),
        ),
        migrations.AlterField(
            model_name='fornitore',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fornitore',
            name='fatturaElettronica',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fattura elettronica'),
        ),
        migrations.AlterField(
            model_name='fornitore',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fornitore',
            name='picf',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='P.iva / CF'),
        ),
        migrations.AlterField(
            model_name='fornitore',
            name='provincia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fornitore',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
