# Generated by Django 2.0 on 2021-01-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisti',
            name='completo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completo'),
        ),
        migrations.AlterField(
            model_name='acquisti',
            name='ordinato',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ordinato'),
        ),
        migrations.AlterField(
            model_name='acquisti',
            name='spedito',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Spedito'),
        ),
    ]
