# Generated by Django 2.0 on 2021-01-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='creato',
            field=models.DateField(auto_now_add=True, verbose_name='Data creazione'),
        ),
    ]
