# Generated by Django 2.0 on 2021-01-13 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisti',
            name='creato',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='data creazione'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acquisti',
            name='prezzo',
            field=models.IntegerField(default='0'),
        ),
    ]
