# Generated by Django 2.0 on 2021-02-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210210_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cognome',
            new_name='PEC',
        ),
        migrations.RenameField(
            model_name='fornitore',
            old_name='cognome',
            new_name='PEC',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='fornitore',
            name='nome',
        ),
        migrations.AddField(
            model_name='cliente',
            name='emailReferente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email referente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='referente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefonoReferente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefono referente'),
        ),
        migrations.AddField(
            model_name='fornitore',
            name='emailReferente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email referente'),
        ),
        migrations.AddField(
            model_name='fornitore',
            name='referente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referente'),
        ),
        migrations.AddField(
            model_name='fornitore',
            name='telefonoReferente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefono referente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fatturaElettronica',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cod. UNIVOCO'),
        ),
        migrations.AlterField(
            model_name='fornitore',
            name='fatturaElettronica',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cod. UNIVOCO'),
        ),
    ]
