# Generated by Django 2.0 on 2021-01-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210113_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acquisti',
            options={'verbose_name': 'Acquisto', 'verbose_name_plural': 'Acquisti'},
        ),
        migrations.AddField(
            model_name='acquisti',
            name='codiceProdotto',
            field=models.CharField(default=123, max_length=100, verbose_name='Codice prodotto'),
            preserve_default=False,
        ),
    ]
