# Generated by Django 2.0 on 2021-01-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210115_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisti',
            name='prezzo',
            field=models.IntegerField(default='0'),
        ),
    ]
