# Generated by Django 2.0 on 2021-01-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210115_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisti',
            name='DDT',
            field=models.FileField(blank=True, null=True, upload_to='DDT_Acquisti/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='acquisti',
            name='fattura',
            field=models.FileField(blank=True, null=True, upload_to='Fattura_Acquisti/%Y/%m/%d'),
        ),
    ]
