# Generated by Django 2.0 on 2021-01-15 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210115_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acquisti',
            old_name='autore',
            new_name='user',
        ),
    ]
