# Generated by Django 2.0 on 2021-01-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210115_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisti',
            name='completo',
        ),
        migrations.AddField(
            model_name='acquisti',
            name='chiuso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='chiuso'),
        ),
        migrations.AddField(
            model_name='acquisti',
            name='pagato',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pagato'),
        ),
        migrations.AddField(
            model_name='acquisti',
            name='ricevuto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ricevuto'),
        ),
        migrations.AlterField(
            model_name='acquisti',
            name='stato',
            field=models.CharField(blank=True, choices=[('ordinato', 'Ordinato'), ('spedito', 'Spedito'), ('ricevuto', 'Ricevuto'), ('pagato', 'Pagato'), ('chiuso', 'Chiuso')], max_length=20),
        ),
    ]
