# Generated by Django 2.0 on 2021-01-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210115_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acquisti',
            old_name='fattura',
            new_name='preventivo',
        ),
    ]
