# Generated by Django 2.0 on 2021-01-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210115_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisti',
            name='DDT',
            field=models.FileField(blank=True, upload_to='DDT_Acquisti/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='acquisti',
            name='preventivo',
            field=models.FileField(blank=True, null=True, upload_to='Fattura_Acquisti/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='acquisti',
            name='stato',
            field=models.CharField(blank=True, choices=[('ordinato', 'Ordinato'), ('spedito', 'Spedito'), ('ricevuto', 'Ricevuto'), ('pagato', 'Pagato'), ('chiuso', 'Chiuso')], max_length=20, null=True),
        ),
    ]
