# Generated by Django 2.0 on 2021-01-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_acquisti_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisti',
            name='fattura',
            field=models.FileField(blank=True, upload_to='fatture_Acquisti/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='acquisti',
            name='track',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tracking'),
        ),
    ]
