# Generated by Django 2.0 on 2021-01-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210115_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisti',
            name='stato',
            field=models.CharField(blank=True, choices=[('ordinato', 'Ordinato'), ('spedito', 'Spedito'), ('ricevuto', 'Ricevuto'), ('pagato', 'Pagato'), ('chiuso', 'Chiuso')], default='Ordinato', max_length=20, null=True),
        ),
    ]
