# Generated by Django 2.0 on 2021-01-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210115_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisti',
            name='preventivo',
            field=models.FileField(upload_to='Fattura_Acquisti/%Y/%m/%d'),
        ),
    ]
