# Generated by Django 2.0 on 2021-01-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210115_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisti',
            name='creato',
            field=models.DateTimeField(verbose_name='Data'),
        ),
    ]
