# Generated by Django 2.0 on 2021-01-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210115_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisti',
            name='ordinato',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ordinato'),
        ),
    ]
