# Generated by Django 2.0 on 2021-02-25 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20210212_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltriFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='pdf_gare_/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='GaraPubblica',
            fields=[
                ('idGara', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='RDO')),
                ('oggetto', models.CharField(max_length=100)),
                ('stato', models.CharField(blank=True, choices=[('Creata', 'Creata'), ('Offerta', 'Offerta'), ('Compilata', 'Compilata'), ('Inviata', 'Inviata'), ('Aggiudicata', 'Aggiudicata'), ('Non aggiudicata', 'Non aggiudicata')], default='Creata', max_length=20, null=True)),
                ('importoLotti', models.PositiveIntegerField(blank=True, default='0', null=True, verbose_name='Importo lotti')),
                ('ultimaModifica', models.DateField(auto_now=True, verbose_name='Ultima moodifica')),
                ('amministrazione', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Cliente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('vendita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Fattura', verbose_name='Vendita')),
            ],
            options={
                'verbose_name': 'Gara Pubblica',
                'verbose_name_plural': 'Gare Pubbliche',
            },
        ),
        migrations.CreateModel(
            name='Lotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiceLotto', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID')),
                ('preventivoFile', models.FileField(blank=True, null=True, upload_to='Preventivi_Lotti/%Y/%m/%d', verbose_name='Preventivo')),
                ('importo', models.PositiveIntegerField(blank=True, default='0', null=True, verbose_name='Importo')),
                ('gara', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_lotto', to='gare.GaraPubblica')),
                ('offerta', models.ManyToManyField(blank=True, related_name='has_lotto', to='main.Fornitore', verbose_name='Offerta')),
            ],
            options={
                'verbose_name': 'Lotto',
                'verbose_name_plural': 'Lotti',
            },
        ),
        migrations.AddField(
            model_name='altrifile',
            name='gara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gare.GaraPubblica'),
        ),
    ]
