# Generated by Django 2.0 on 2021-02-25 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='altrifile',
            name='lotto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gare.Lotto'),
            preserve_default=False,
        ),
    ]
