# Generated by Django 2.0 on 2021-02-25 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gare', '0003_auto_20210225_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='pdf_gare_/%Y/%m/%d')),
                ('lotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gare.Lotto')),
            ],
        ),
    ]
