# Generated by Django 2.0 on 2021-02-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gare', '0004_lottofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottofile',
            name='lotto',
        ),
        migrations.RemoveField(
            model_name='garapubblica',
            name='file',
        ),
        migrations.AddField(
            model_name='lotto',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='File_gare/%Y/%m/%d', verbose_name='Altri file'),
        ),
        migrations.DeleteModel(
            name='LottoFile',
        ),
    ]
