# Generated by Django 2.0 on 2021-01-14 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiceProdotto', models.CharField(max_length=100, verbose_name='Codice prodotto')),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('costruttore', models.CharField(blank=True, max_length=100)),
                ('modello', models.CharField(blank=True, max_length=100)),
                ('numeroSerie', models.CharField(blank=True, max_length=100, verbose_name='Numero serie')),
                ('classe', models.CharField(blank=True, max_length=100)),
                ('creato', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cliente')),
                ('fornitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Fornitore')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivi',
            },
        ),
        migrations.CreateModel(
            name='Riparazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRiparazione', models.DateField(verbose_name='Data riparazione')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cliente')),
                ('dispositivo', models.ManyToManyField(related_name='riparazioni', to='assistenza.Prodotti')),
            ],
            options={
                'verbose_name': 'Riparazione',
                'verbose_name_plural': 'Riparazioni',
            },
        ),
        migrations.CreateModel(
            name='Verifica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificaElettrica', models.BooleanField(verbose_name='Verifica elettrica')),
                ('verificaFunzionale', models.BooleanField(verbose_name='Verifica funzionale')),
                ('dataVerifica', models.DateField(verbose_name='Data verifica')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cliente')),
                ('dispositivo', models.ManyToManyField(related_name='verifiche', to='assistenza.Prodotti')),
            ],
            options={
                'verbose_name': 'Verifica',
                'verbose_name_plural': 'Verifiche',
            },
        ),
    ]
