# Generated by Django 2.0 on 2021-02-08 16:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiceProdotto', models.CharField(max_length=100, verbose_name='Codice prodotto')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('costruttore', models.CharField(blank=True, max_length=100, null=True)),
                ('modello', models.CharField(blank=True, max_length=100, null=True)),
                ('numeroSerie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero serie')),
                ('classe', models.CharField(blank=True, max_length=100, null=True)),
                ('creato', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cliente')),
                ('fornitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Fornitore')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivi',
            },
        ),
        migrations.CreateModel(
            name='Riparazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiceID', models.CharField(max_length=100, verbose_name='ID')),
                ('stato', models.CharField(blank=True, choices=[('creatoIniziale', 'Pratica creata'), ('richiesta', 'Richiesta'), ('preventivo', 'Preventivo'), ('autorizzazione', 'Autorizzazione'), ('eseguita', 'Eseguita'), ('verifiche', 'Verifiche'), ('fatturaEmessa', 'Fattura emessa'), ('pagato', 'pagato'), ('chiuso', 'chiuso')], default='creatoIniziale', max_length=20, null=True)),
                ('ultimaModifica', models.DateTimeField(blank=True, null=True, verbose_name='Ultima moodifica')),
                ('noteIniziali', models.CharField(blank=True, max_length=300, null=True, verbose_name='Note')),
                ('richiestaFile', models.FileField(blank=True, upload_to='Richiesta_Riparazione/%Y/%m/%d', verbose_name='Richiesta')),
                ('preventivoFile', models.FileField(blank=True, upload_to='Preventivi_Riparazione/%Y/%m/%d', verbose_name='Preventivo')),
                ('autorizzazioneFile', models.FileField(blank=True, upload_to='Autorizzazione_Riparazione/%Y/%m/%d', verbose_name='Autorizzazione')),
                ('fatturaFile', models.FileField(blank=True, null=True, upload_to='Fattura_riparazione/%Y/%m/%d', verbose_name='Fattura')),
                ('ricevutaPagamentoFile', models.FileField(blank=True, null=True, upload_to='Ricevuta_riparazione/%Y/%m/%d', verbose_name='Ricevuta')),
                ('tipoPagamento', models.CharField(blank=True, choices=[('bonifico', 'bonifico'), ('assegno', 'assegno'), ('carta', 'carta'), ('paypal', 'paypal'), ('cassa', 'cassa')], max_length=20, null=True, verbose_name='Pagato con')),
                ('prezzo', models.FloatField(blank=True, default='0', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='importo')),
                ('flag', models.BooleanField(default=False)),
                ('statoX', models.CharField(blank=True, max_length=20, null=True)),
                ('creatoIniziale', models.DateTimeField(blank=True, null=True, verbose_name='Creato')),
                ('richiesta', models.DateTimeField(blank=True, null=True, verbose_name='Richiesta')),
                ('preventivo', models.DateTimeField(blank=True, null=True, verbose_name='Preventivo')),
                ('autorizzazione', models.DateTimeField(blank=True, null=True, verbose_name='Autorizzazione')),
                ('eseguita', models.DateTimeField(blank=True, null=True, verbose_name='Eseguita')),
                ('verifiche', models.DateTimeField(blank=True, null=True, verbose_name='Verifiche')),
                ('fatturaEmessa', models.DateTimeField(blank=True, null=True, verbose_name='Fattura emessa')),
                ('pagato', models.DateTimeField(blank=True, null=True, verbose_name='Pagato')),
                ('chiuso', models.DateTimeField(blank=True, null=True, verbose_name='Chiuso')),
                ('RIT', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Rapporti', verbose_name='RIT')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cliente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Riparazione',
                'verbose_name_plural': 'Riparazioni',
            },
        ),
        migrations.CreateModel(
            name='Verifica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiceID', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID')),
                ('stato', models.CharField(blank=True, choices=[('creatoIniziale', 'Pratica creata'), ('richiesta', 'Richiesta'), ('preventivo', 'Preventivo'), ('eseguita', 'Eseguito'), ('elaborazione', 'Elaborazione'), ('inviata', 'Inviate'), ('pagato', 'Pagato'), ('consegnato', 'Consegnato'), ('chiuso', 'Chiuso')], default='creatoIniziale', max_length=20, null=True)),
                ('ultimaModifica', models.DateTimeField(blank=True, null=True, verbose_name='Ultima moodifica')),
                ('verificaFunzionale', models.PositiveIntegerField(blank=True, default='0', null=True, verbose_name='V. F.')),
                ('prezzo', models.FloatField(blank=True, default='0', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='importo')),
                ('noteIniziali', models.CharField(blank=True, max_length=300, null=True, verbose_name='Note')),
                ('richiestaFile', models.FileField(blank=True, null=True, upload_to='Richiesta_Verifica/%Y/%m/%d', verbose_name='Richiesta')),
                ('preventivoFile', models.FileField(blank=True, null=True, upload_to='Preventivi_Verifica/%Y/%m/%d', verbose_name='Preventivo')),
                ('verificaElettrica', models.PositiveIntegerField(blank=True, default='0', null=True, verbose_name='V. E.')),
                ('cei', models.CharField(blank=True, max_length=100, null=True, verbose_name='CEI')),
                ('outputStrumentoFile', models.FileField(blank=True, null=True, upload_to='Output_strumento/%Y/%m/%d', verbose_name='Output strumento')),
                ('schedaFile', models.FileField(blank=True, null=True, upload_to='Scheda_Verifica/%Y/%m/%d', verbose_name='Scheda')),
                ('fatturaFile', models.FileField(blank=True, null=True, upload_to='Fattura_Verifica/%Y/%m/%d', verbose_name='Fattura')),
                ('ricevutaPagamentoFile', models.FileField(blank=True, null=True, upload_to='Ricevuta_Verifica/%Y/%m/%d', verbose_name='Ricevuta')),
                ('tipoPagamento', models.CharField(blank=True, choices=[('bonifico', 'bonifico'), ('assegno', 'assegno'), ('carta', 'carta'), ('paypal', 'paypal'), ('cassa', 'cassa')], max_length=20, null=True, verbose_name='Pagato con')),
                ('noteFinali', models.CharField(blank=True, max_length=300, null=True, verbose_name='Note')),
                ('creatoIniziale', models.DateTimeField(blank=True, null=True, verbose_name='Creato')),
                ('richiesta', models.DateTimeField(blank=True, null=True, verbose_name='Richiesta')),
                ('preventivo', models.DateTimeField(blank=True, null=True, verbose_name='Preventivo')),
                ('eseguita', models.DateTimeField(blank=True, null=True, verbose_name='Eseguita')),
                ('elaborazione', models.DateTimeField(blank=True, null=True, verbose_name='Elaborazione')),
                ('inviata', models.DateTimeField(blank=True, null=True, verbose_name='Inviata')),
                ('pagato', models.DateTimeField(blank=True, null=True, verbose_name='Pagato')),
                ('consegnato', models.DateTimeField(blank=True, null=True, verbose_name='Consegnato')),
                ('chiuso', models.DateTimeField(blank=True, null=True, verbose_name='Chiuso')),
                ('flag', models.BooleanField(default=False)),
                ('statoX', models.CharField(blank=True, max_length=20, null=True)),
                ('RIT', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Rapporti', verbose_name='RIT')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cliente')),
                ('prodotti', models.ManyToManyField(blank=True, related_name='verifica_related', to='assistenza.Prodotti')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Verifica',
                'verbose_name_plural': 'Verifiche',
            },
        ),
        migrations.AddField(
            model_name='riparazione',
            name='verifica',
            field=models.ManyToManyField(blank=True, related_name='riparazione', to='assistenza.Verifica', verbose_name='Verifiche'),
        ),
    ]
