# Generated by Django 2.0 on 2021-02-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotti',
            name='inventario',
            field=models.CharField(max_length=50, null=True, verbose_name='Inventario'),
        ),
        migrations.AddField(
            model_name='prodotti',
            name='normativa',
            field=models.CharField(choices=[('norma1', '12469'), ('norma2', '14175'), ('norma3', '62-5'), ('norma4', '62-13'), ('norma5', '66-5')], default='norma1', max_length=20, verbose_name='Normativa'),
        ),
    ]
