# Generated by Django 2.0 on 2021-02-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenza', '0002_auto_20210212_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='normativaCodice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=154)),
            ],
        ),
        migrations.RemoveField(
            model_name='prodotti',
            name='normativa',
        ),
        migrations.AddField(
            model_name='prodotti',
            name='normativa',
            field=models.ManyToManyField(to='assistenza.normativaCodice'),
        ),
    ]
