# Generated by Django 2.0 on 2021-02-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenza', '0005_auto_20210212_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifica',
            name='dataVerifica',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data verifica'),
        ),
    ]
