# Generated by Django 2.0 on 2021-02-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenza', '0007_auto_20210216_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifica',
            name='tornaIndietro',
            field=models.BooleanField(default=False),
        ),
    ]
