# Generated by Django 2.0 on 2021-02-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenza', '0008_verifica_tornaindietro'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifica',
            name='ceiMultiple',
            field=models.CharField(blank=True, default='C.E.I.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='verifica',
            name='cei',
            field=models.ManyToManyField(blank=True, related_name='has_verifica', to='assistenza.normativaCodice', verbose_name='CEI'),
        ),
        migrations.AlterField(
            model_name='verifica',
            name='noteFinali',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Note finali'),
        ),
        migrations.AlterField(
            model_name='verifica',
            name='noteIniziali',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Note iniziali'),
        ),
        migrations.AlterField(
            model_name='verifica',
            name='verificaElettrica',
            field=models.PositiveIntegerField(blank=True, default='0', null=True, verbose_name='Verifica elettrica'),
        ),
        migrations.AlterField(
            model_name='verifica',
            name='verificaFunzionale',
            field=models.PositiveIntegerField(blank=True, default='0', null=True, verbose_name='Verifica funzionale'),
        ),
    ]
