# Generated by Django 2.0 on 2021-02-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenza', '0009_auto_20210222_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifica',
            name='ceiMultiple',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='C.E.I.'),
        ),
    ]
