# Generated by Django 2.0 on 2021-02-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenza', '0011_auto_20210222_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifica',
            name='ceiMultiple',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verifica',
            name='stato',
            field=models.CharField(blank=True, choices=[('0', 'Pratica creata'), ('1', 'Richiesta'), ('2', 'Preventivo'), ('3', 'Eseguito'), ('4', 'Elaborazione'), ('5', 'Inviate'), ('6', 'Pagato'), ('7', 'Consegnato'), ('8', 'Chiuso')], default='creatoIniziale', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='verifica',
            name='verificaElettrica',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Verifica elettrica'),
        ),
    ]
