# Generated by Django 2.0 on 2021-02-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistenza', '0015_auto_20210222_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifica',
            name='ceiMultiple',
        ),
    ]
