# Generated by Django 2.0 on 2021-02-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenza', '0016_remove_verifica_ceimultiple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifica',
            name='richiestaFile',
            field=models.FileField(blank=True, null=True, upload_to='Richiesta_Verifica/%Y/%m/%d', verbose_name='Richiesta'),
        ),
        migrations.AlterField(
            model_name='verifica',
            name='stato',
            field=models.CharField(blank=True, choices=[('0', 'Pratica creata'), ('1', 'Richiesta'), ('2', 'Preventivo'), ('3', 'Eseguito'), ('4', 'Elaborazione'), ('5', 'Inviate'), ('6', 'Pagato'), ('7', 'Consegnato'), ('8', 'Chiuso')], default='0', max_length=20, null=True),
        ),
    ]
