# Generated by Django 2.0 on 2021-02-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenza', '0017_auto_20210222_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifica',
            name='stato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='verifica',
            name='verificaElettrica',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='V.E.'),
        ),
        migrations.AlterField(
            model_name='verifica',
            name='verificaFunzionale',
            field=models.PositiveIntegerField(blank=True, default='0', null=True, verbose_name='V.F.'),
        ),
    ]
