# Generated by Django 3.1.7 on 2021-02-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenza', '0019_auto_20210224_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifica',
            name='stato',
            field=models.CharField(blank=True, choices=[('0', 'Pratica creata'), ('1', 'Richiesta'), ('2', 'Preventivo'), ('3', 'Eseguito'), ('4', 'Elaborazione'), ('5', 'Inviate'), ('6', 'Pagato'), ('7', 'Consegnato'), ('8', 'Chiuso'), ('Invisible', [('attivo', 'attivo'), ('in scadenza', 'in scadenza'), ('scaduto', 'scaduto')])], default='0', max_length=20, null=True),
        ),
    ]
