# Generated by Django 3.1.7 on 2021-02-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenza', '0020_auto_20210224_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifica',
            name='stato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
